# Generated by Django 5.2.7 on 2025-10-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network_link", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="name",
        ),
    ]
